### ISSUE TITLE
Revoir la vue marque blanche

### ISSUE THREAD

**Issue by clemoigno** [megalis-bretagne/opendata-marqueblanche#10]
Actuellement, la vue marque blanche est une 'simple' vue sur le filesystem des fichiers contenus sur le serveur.
Cette vue est très simple et du coup facile à mettre en oeuvre mais ne permet pas de filtre/recherche/amélioration de l'affichage (sur les nom de fichiers par exemple Vs les libellés des objets des délibérations)

L'idée serait de reprendre la vue du type de résultat de 'recherche'.

**Comment by clemoigno** [comment]
Sous-tâches :
#5 
#4

**Comment by clemoigno** [comment]
D'ailleurs me concernant, je trouverais bien dans la vue de pouvoir voir une délibération et ses annexes liées.
Actuellement, les délibérations et les annexes se trouvent au même niveau, sans lien entre elles.

**Comment by spelhate** [comment]
Je propose également d'adapter la vue de la marque blanche pour conserver un header statique lors du scroll 
L'idée serait de fixer ce qui est entouré en jaune dans l'illustration ci dessous et de rendre scrollable uniquement ce qui est entouré en rouge.
![image](https://user-images.githubusercontent.com/1793792/176626271-baa4493f-31c5-4996-80b7-7fee52a54e36.png)
Qu'en pensez vous ?
