### ISSUE TITLE
Affichage de la date de publication

### ISSUE THREAD

**Issue by StephaneLEGENDRE** [megalis-bretagne/opendata-marqueblanche#12]
afin de répondre à l'obligation entrant en vigueur au 1er juillet 2022, serait il possible d'ajouter une colonne en face de chaque acte indiquant la date de publication ?
cela pourrait être (de façon automatique) la date à laquelle le fichier est déposé sur opendata ...

Merci  Vous

S. LEGENDRE

**Comment by lvinsonneau** [comment]
@yguenneugues @ElodieTessier @spelhate  : c'est d'autant plus important que, légalement, l'acte doit être publié pendant 2 mois pour être opposable. 
Pas obligatoirement une colonne, mais en tout cas, il y a bien ce besoin de voir figurer la date de publication de l'acte a priori.

**Comment by lvinsonneau** [comment]
Suite à discussion en interne (@ElodieTessier @spelhate), et dans la perspective de l'affichage de la date de publication, on préconise de : 

-    ne pas afficher de date pour tous les actes publiés avant le 1er juillet (si ce n'est pas trop contraignant au niveau développement)
-    par "date de publication", ce n'est pas la date de première publication mais bien la date (la dernière) où la collectivité a décidé de publier son acte. Donc si elle publie à la date 1, puis dépublie, puis republie à la date 2, c'est la date 2 que l'on garde.

**Comment by yguenneugues** [comment]
ajout de la date de publication réalisée
