### ISSUE TITLE
Récupération des fichiers non transmis au contrôle de légalité

### ISSUE THREAD

**Issue by StephaneLEGENDRE** [megalis-bretagne/opendata-marqueblanche#13]
toujours pour répondre à l'obligation du 1er Juillet 2022 imposant de publier l'ensemble des actes.

serait il possible de récupérer les actes qui ne sont pas transmis au contrôle de légalité ?
Annexes dont la Préfecture ne veut pas par exemple.

Ce pourrait être à partir de la page dans laquelle on saisi les documents à transmettre, 
Où il pourrait être ajouté plusieurs fichiers qui ne seront pas transmis au contrôle de légalité mais qui, une fois le retour du document signé de la Préfecture, pourraient être publiés en même temps que l'acte et les pièces transmises sur l'OPENDATA ...

merci à vous.

S. LEGENDRE

**Comment by lvinsonneau** [comment]
@StephaneLEGENDRE :  on va s'attacher dans un 1er temps à essayer d'élargir la sphère de publication en opendata sur ce qui est transféré au contrôle de légalité et qui n'en fait pas partie pour le moment (cf. https://github.com/megalis-bretagne/opendata-extraction/issues/13).

Mais on note se besoin pour l'étudier par la suite. En attendant et dans la perspective du 1er juillet 2022, il sera nécessaire que les collectivités le prévoit de leur côté.

**Comment by lvinsonneau** [comment]
@StephaneLEGENDRE : on a bien avancé en interne Mégalis (grâce à @spelhate et @Cridard !) sur la création d'un nouveau flux sous pastell appelé "Hors Préfecture", donc bientôt (le 7 novembre si tout va bien et sauf impondérable), nous devrions mettre en production ce nouveau flux. Les actes non soumis au contrôle de légalité devraient ainsi être disponibles sur le module de Gestion de publication ainsi que sur la marque-blanche.

**Comment by yguenneugues** [comment]
lié à https://github.com/megalis-bretagne/opendata-extraction/issues/24

**Comment by spelhate** [comment]
Je remarque qu'il n'est pas possible d filtrer les actes hors préfecture dans la marque blanche. Il manque l'item "Hors préfecture" dans la liste déroulante
.
![image](https://user-images.githubusercontent.com/1793792/199468599-6e1fffe2-d4f3-4ae0-8e62-fb9f6e7b9483.png)
