### ISSUE TITLE
Ajour bouton "i" ou "en savoir +"

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-marqueblanche#14]
Voir la possibilité d'ajouter une information ("en savoir +") dans l'interface de la marque-blanche pour ajouter sources du projet Mégalis + logo France Relance

**Comment by gautierrog** [comment]
A mettre dans la nouvelle MQ delib

**Comment by lvinsonneau** [comment]
texte initié ici : https://nextcloud.megalis.bretagne.bzh/apps/files/?dir=/PARTENARIAT%20TECHNIQUE/ACTES&fileid=144372
(A relire et valider par tous)

**Comment by gautierrog** [comment]
https://github.com/megalis-bretagne/pages-publiques/blob/main/apropos-mq-delibs.md

Je vous ai donné les droits sur le repository https://github.com/megalis-bretagne/pages-publiques
C'est un repo public, que vous avez le droit de modifier. 
Il y a un fichier https://github.com/megalis-bretagne/pages-publiques/blob/main/apropos-mq-delibs.md en son sein. 
Je vous propose de travailler sur ce dernier afin que vous ayez la main sur la page "en savoir plus" de la mq delibs.

Si on se base sur ce modèle, chaque modif mettrait 5 minutes à être prise en compte.

**Comment by lvinsonneau** [comment]
OK, super, merci @gautierrog 
Je vais tester en ajoutant les logos France Relance : où penses-tu que nous ajoutions les images qui viendront agrémenter les pages futures ? Tu crées un répertoire ad hoc ?

**Comment by gautierrog** [comment]
Oh, pour les images je les ai ajoutées dans le document déjà. 

On peut bien sûr essayer avec un répertoire dans le repository

Mais, actuellement, sur https://github.com/megalis-bretagne/pages-publiques/blob/main/apropos-mq-delibs.md,
Lors de l'édition, elles sont embarquées à la fin du document:

![image](https://user-images.githubusercontent.com/110091547/206655642-5caff351-6602-415d-a7a1-0db6bb488043.png)

Elles n'apparaissent pas via l'aperçu dans github mais au sein de la marque blanche, elles apparaitront bel et bien.

**Comment by gautierrog** [comment]
Sur la pré-production (https://data-preprod.megalis.bretagne.bzh/marqueblanche-refonte/), vous avez maintenant un lien "en savoir plus":

![image](https://user-images.githubusercontent.com/110091547/206661446-dd15f8cd-bb82-45a9-93d3-29ec155e0e35.png)

**Comment by ElodieTessier** [comment]
Super, merci @gautierrog<https://github.com/gautierrog> !


Elodie Tessier
Chargée de mission accompagnement & data
Ligne directe : 02 30 95 10 53 / Portable : 07 72 06 53 29

Direction Modernisation des administrations et Services numériques
Mégalis Bretagne - Syndicat mixte de coopération territoriale
ZAC des champs blancs - 15, rue Claude Chappe - Bâtiment B - Cesson Sévigné
https://www.megalis.bretagne.bzh/

________________________________
De : gautierrog ***@***.***>
Envoyé : vendredi 9 décembre 2022 09:45
À : megalis-bretagne/opendata-marqueblanche ***@***.***>
Cc : Elodie Tessier ***@***.***>; Assign ***@***.***>
Objet : Re: [megalis-bretagne/opendata-marqueblanche] Ajour bouton "i" ou "en savoir +" (Issue #14)


Sur la pré-production (https://data-preprod.megalis.bretagne.bzh/marqueblanche-refonte/), vous avez maintenant un lien "en savoir plus":

[image]<https://user-images.githubusercontent.com/110091547/206661446-dd15f8cd-bb82-45a9-93d3-29ec155e0e35.png>

**Comment by lvinsonneau** [comment]
Pour avis (@gautierrog @spelhate  et d'autres) : pour les modifs éventuelles, on commit directement dans la main branch  ? ou autre process ?

**Comment by lvinsonneau** [comment]
Et c'est quoi le process type recommandé pour ajouter une image ?

**Comment by gautierrog** [comment]
Pour les modifications, ce qui est commité dans la branche `main` se répercutera dans les 5 minutes sur la MQ delibs.

Quant aux images, voici comment on peut procéder:

- Ajouter une image au repository (exemple: https://github.com/megalis-bretagne/pages-publiques/blob/main/megalis-logo-web.png) - un drag'n' drop de l'image vers la page web du repo permet d'ajouter l'image au repo
- Récupérer le lien de l'image, via le bouton download comme montré ci-dessous:

![image](https://user-images.githubusercontent.com/110091547/206695056-622828bc-5395-462c-8e7c-21ff5b6064f8.png)

Une fois cliqué copier l'url de la page qui s'affiche (ici: https://raw.githubusercontent.com/megalis-bretagne/pages-publiques/main/megalis-logo-web.png)

- Finalement, pour ajouter une image au document, éditer le fichier .md:

![image](https://user-images.githubusercontent.com/110091547/206695427-bb800d17-7c85-4b25-a2c5-c3df507ecdd0.png)

Et pour ajouter une image, voici la syntaxe:

`![Logo megalis](https://raw.githubusercontent.com/megalis-bretagne/pages-publiques/main/megalis-logo-web.png)`

Le texte entre crochet est une description de l'image, le lien entre parenthèse est le lien recupèré peu avant.


Faire comme décrit ci-dessus permet aussi de voir les images dans l'aperçu des modification.

**Comment by lvinsonneau** [comment]
merci @gautierrog

**Comment by spelhate** [comment]
Bonjour.
C'est curieux, on dirait que les images sont stockées dans le fichier .md : https://github.com/megalis-bretagne/pages-publiques/blob/d0bc56e87bab8e4b854fc1316f13d0728c8957eb/apropos-mq-delibs.md?plain=1#L27

**Comment by gautierrog** [comment]
Oui, initialement j'ai embarqué les images dans le document directement (cf. quelques commentaires ci-dessus). Je viens de tout remplacer par des liens.
