### ISSUE TITLE
Compréhension de la méthode d'indexation ?

### ISSUE THREAD

**Issue by jerbou** [megalis-bretagne/opendata-marqueblanche#15]
Bonjour,

Le projet a déja été présenté à l'Agence Régional du Numérique (ARNia) de BFC, pour autant, disposez vous d’éléments de méthodologie sur comment est réalisé l'indexation des informations en backoffice ?
Dois je poser la question plus directement sur le projet "source" ) sur le gitlab 
https://gitlab.adullact.net/gironde-numerique/data-search-engine
?

D'avance Merci,
jerome boutet

**Comment by yguenneugues** [comment]
Bonjour,

L'indexation des documents est réalisée avec Apache Solr en repectant un schéma commun (structure du documents en base de données) dans le projet de gironde numérique et le notre. Cela permet de réutiliser le même outil / code de marque blanche, site web permettant de consulter, rechercher des actes et insérable en mode iframe dans un site internet.


Cependant nous n'utilisons pas la même méthode pour récupérer et indexer les documents issu de Pastell


Dans le cas de gironde numérique, [un connecteur pastell a été developpé](https://gitlab.adullact.net/gironde-numerique/citizen-data). Celui-ci permet de récupérer et indexer dans apache solr les documents directement depuis pastell. Pour cela il faut ajouter ce connecteur à votre pastell, le paramétrer et l'associer à vos flux pour l'utiliser. L'indexation est alors réalisée en php à l'aide d'une librairie pour faire du CURL directement vers solr, [ici le code qui réalise l'insert dans solr](https://gitlab.adullact.net/gironde-numerique/citizen-data/-/blob/master/connecteur/indexeur/lib/SolrConsumer.php)


Dans notre cas, nous avons fait le choix d'utiliser un connecteur standard pastell pour récupérer les documents (connecteur GED sftp). Celui-ci nous permet de récupérer automatiquement dans un dossier les documents et leurs métadonnées à indexer.
Un programme python nous permet alors de détecter les nouveaux actes et de lancer le traitement d'indexation.
Nous avons utilisé la librairie [pysolr](https://pypi.org/project/pysolr/) pour faciliter les interactions avec apache solr.

L'indexation / insertion est réalisée en 3 étapes:

1. Extraction du documents (mode extractOnly=true)
2. Ajout des métadonnées au document précédemment extrait ( siren, date_de_lacte, date_publication ....)
3. insert dans solr

Ci-dessous le code qui permet de faire ces étapes:
```python

with open(acte.path, 'rb') as fh:
    try:
        solr = solr_connexion()
        #Etape 1: extraction du document
        data = solr.extract(fh, extractOnly=True)

        # Etape 2: Ajout des métadonnées
        # generation du hash
        hash = hashlib.md5(fh.read()).hexdigest()
        traiter_actes(data, hash, infoEtablissement, publication, acte, isPj=False)

        # Etape 3:insert dans apache solr
        solr.add(data['metadata'])

    except Exception as e:
        db_sess = db.session
        publication.etat = '3'
        db_sess.add(publication)
        db_sess.commit()
        logging.exception("Erreur lors de la publication de l'acte: %s" % acte)
        raise e

```

**Comment by jerbou** [comment]
Merci pour cette réponse complète.
