### ISSUE TITLE
Le nom des annexes des actes

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-marqueblanche#17]
Dans la nouvelle vue, le nom des annexes des actes est le même que celui de l'acte.
Pour les différencier, les annexes sont en grisé.
Certaines collectivités ne s'y retrouvent pas.

Est ce qu'il serait possible/opportun d'ajouter le mot ANNEXE à l'objet des annexes ?
Ou est ce le temps que les collectivités s'imprègnent de ce nouvel outil ?

La question reste ouverte de mon côté.

**Comment by lvinsonneau** [comment]
Peut-être que déjà en répondant à la demande d'évolution suivante : https://github.com/megalis-bretagne/opendata-marqueblanche/issues/18 , on améliore l'expérience utilisateur et la distinction entre document et annexe ?
