### ISSUE TITLE
Emplacement des annexes dans la marque blanche

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-marqueblanche#18]
Bonjour,
Dans la nouvelle vue, les annexes sont situées au dessus des actes.
Serait-il plus logique de les mettre en dessous ?
![image](https://user-images.githubusercontent.com/97222408/178211304-00c455a5-57a9-4b1c-8139-f7687904ae65.png)

**Comment by lvinsonneau** [comment]
@yguenneugues : va regarder s'il peut rapidement corriger, mais sinon, sera revu avec la nouvelle version (design revu) prévue pour la rentrée.

**Comment by clemoigno** [comment]
@ElodieTessier Logiquement cela a été traité. C'est OK pour toi ?
@yguenneugues ==> A cloturer ?

**Comment by ElodieTessier** [comment]
@clemoigno c'est OK pour moi. Merci.
