### ISSUE TITLE
Ajouter associations connecteurs Open Data sur les dossiers "autres-studio", "actes-reglementaires-studio","arretes-individuels-studio"

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-marqueblanche#19]
Bonjour,
sur l'outil d'admin des publications opendata (https://data-publication.megalis.bretagne.bzh/pastell) , est-il possible d'ajouter les associations automatiques sur les dossiers pour lesquels le paramétrage opendata a été récemment ajouté  : 
"autres-studio", "actes-reglementaires-studio" et "arretes-individuels-studio"
Merci.

**Comment by yguenneugues** [comment]
installé en prod
