### ISSUE TITLE
MARQUE-BLANCHE - Critères/champs de recherche

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-marqueblanche#2]
Sur la marque-blanche, sur quels champs (ou autres critères) sont basées les recherches parmi les publications ?

**Comment by clemoigno** [comment]
@lvinsonneau 
La recherche fonctionne sur tous les champs (objet, code matière, nom matière, contenu du fichier soumis)

**Comment by lvinsonneau** [comment]
ok, merci @clemoigno
