### ISSUE TITLE
Récupération des annexes tamponnées par la préfecture

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-marqueblanche#21]
Bonjour,

dans la marque blanche serait-il possible de mettre les annexes tamponnées par la préfecture, à la place des annexes non tamponnées actuellement publiées en OD.
Exemple sur cette délibération avec annexes, 
COMMUNE de MECE , SIREN : 213501703 no acte : 202207280101 : 
lien sur la marque blanche d'une des annexes :  https://data.megalis.bretagne.bzh/OpenData/213501703/Deliberation/2022/470e7402b13d83be4eacb09358549e65f4542d8808b4be27ebdfec2788364462.pdf
et lien pastell de cette délibération : 
https://pastell.megalis.bretagne.bzh/Document/detail?id_d=qzfMTuR&id_e=92&page=3

**Comment by yguenneugues** [comment]
pour récupérer les annexes tamponnées nous devons reparamétrer l'ensemble des connecteurs **GED pastell** afin de "mapper" les annexes tamponnées à la place des annexes non tamponnées.

remplacer:
autre_document_attache:%autre_document_attache%
par: 
autre_document_attache:%annexes_tamponnees%


![image](https://user-images.githubusercontent.com/10934427/188412410-88d6c988-a8e7-48db-a5a2-8a10009b8860.png)

**Comment by gautierrog** [comment]
A voir au retour de @spelhate pour utiliser les script de maj pastell

**Comment by gautierrog** [comment]
Dispo pour quelques collectivités.
Sera dispo pour toutes collectivités après maj connecteurs pastell en v2. ( cf @spelhate et https://github.com/orgs/megalis-bretagne/projects/2#card-89186777). Pas de dev à prevoir.

**Comment by gautierrog** [comment]
Connecteurs mis à jour en v2.
