### ISSUE TITLE
Incohérence données sur marque blanche délib et annexe SIREN différents

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-marqueblanche#22]
Bonjour,

une collectivité "CIAS De loudeac Commuanuté" (20007706300010)  nous a remonté des incohérences sur leur marque blanche ou des documents d'autres collectivités (Minihic sur Rance) apparaissent : 
cf copie écran et lien PASTELL sur les docs en question : 
https://pastell.megalis.bretagne.bzh/Document/detail?id_d=iPz00Kq&id_e=774     lien pastell de la délib en question de minihic (pas d'annexe sur cette délib)

https://pastell.megalis.bretagne.bzh/Document/detail?id_d=981UicP&id_e=3219    lien pastell de la delib du CIAS de LOUDEAC CO
https://data.megalis.bretagne.bzh/?siren=200077063%20title=%22Marque%20blanche%20open%20data%22   lien marque blanche

![image](https://user-images.githubusercontent.com/97181939/191508128-73408bfd-7e40-4821-8700-eb5745492290.png)

**Comment by clemoigno** [comment]
C'est un problème dans le lien a priori.
Ce lien renvoie bien uniquement les actes  du CIAS Loudéac : https://data.megalis.bretagne.bzh/?siren=200077063

Par contre le d'avoir la suite du lien _%20title="Marque%20blanche%20open%20data"_ génère du bruit ...

**Comment by spelhate** [comment]
Est ce qu'on sait comment ce lien a été construit https://data.megalis.bretagne.bzh/?siren=200077063%20title=%22Marque%20blanche%20open%20data%22  ?
manuellement ?
A la lecture du lien on comprend qu'il y a deux paramètres d'URL **siren** et **title** sauf que le séparateur de paramètre **&** n'est pas ici présent Une URL correcte aurait été : https://data.megalis.bretagne.bzh/?siren=200077063&title=Marque%20blanche%20open%20data

**Comment by Cridard** [comment]
merci @clemoigno  @spelhate pour les infos, à y regarder de plus près il manque des double quote dans son iframe, je pense que le pb vient de là, je valide avec la co et je reviens vers vous pour fermer cette issue.

**Comment by spelhate** [comment]
Je viens de trouver l'origine du problème dans le code grâce aux remarques de @Cridard 
Le snippet marque blanche est mal encodé. Il manque les double quotes pour délimiter la valeur de **src**

https://github.com/megalis-bretagne/opendata-frontapp/blob/c0c1bdd4d5350c416965808568f42747729fea3e/src/app/components/marque-blanche/marque-blanche.component.ts#L39-L41

Au lieu de 
```javascript
'<iframe referrerpolicy="strict-origin-when-cross-origin" style="border: 0;" src=' + url +
      ' title="Marque blanche open data" width="100%" height="600">\n' +
      '</iframe>';
```

Il faut ça 
```javascript
'<iframe referrerpolicy="strict-origin-when-cross-origin" style="border: 0;" src="' + url +
      '" title="Marque blanche open data" width="100%" height="600">\n' +
      '</iframe>';
```

**Comment by spelhate** [comment]
En résumé, le problème vient du fait que l'url de la source n'est pas encadrée par des double quotes. De plus title n'est pas un paramètre utilisée par la marque blanche, et donc contrairement à ce que j'indiquais un peu plus haut, il ne faut pas ajouter un & entre le siren et le title.  title est ici un attribut html de l(iframe et non un paramètre d'url de la marque blanche. J'espère ne pas avoir perdu des gens en route avec mes explications...

**Comment by Cridard** [comment]
no! parfait @spelhate  ;)

**Comment by lvinsonneau** [comment]
@spelhate : donc il manque des quote dans notre tutoriel : https://services.megalis.bretagne.bzh/tutoriel/utiliser-la-marque-blanche-opendata/ ?
Côté mviewer Mégalis, je te laisse vérifier/modifier ?

**Comment by clemoigno** [comment]
Nan @lvinsonneau , ilmanque les quotes dans le code qui génère le snippet sur l'application pro. C'est pour @yguenneugues .

**Comment by lvinsonneau** [comment]
okèche, merci @clemoigno

**Comment by spelhate** [comment]
> Côté mviewer Mégalis, je te laisse vérifier/modifier ?

Il n'y a pas de problèmes dans mviewer. Les quotes sont bien présentes 
![image](https://user-images.githubusercontent.com/1793792/191744616-222bce64-2ea5-4253-8f79-c0d770285920.png)

Et pour le tuto, c'est bon également.

**Comment by spelhate** [comment]
Je viens de faire une PR à toutes fins utiles : https://github.com/megalis-bretagne/opendata-frontapp/pull/11
