### ISSUE TITLE
Demande pour modifier l'aspect de la iframe Marque Blanche

### ISSUE THREAD

**Issue by gperucca** [megalis-bretagne/opendata-marqueblanche#23]
Un utilisateur nous remonte le souhait de pouvoir modifier la police d'écriture dans la iframe . Est ce possible ?

Son besoin : 

Les lettre P et G par exemple qui sont tronquées dans leur hauteur
La suppression de la majuscule en gras dans le titre du document.

![image](https://user-images.githubusercontent.com/114136851/191681224-0df02ac0-f515-4bbe-b0cd-5031186b0028.png)

**Comment by lvinsonneau** [comment]
Je souhaiterais avoir l'avis de la communauté sur ces 2 demandes d'évolution : 

- Les lettre P et G par exemple qui sont tronquées dans leur hauteur : @yguenneugues : est-ce faisable facilement ?
- La suppression de la majuscule en gras dans le titre du document : @ElodieTessier : est-ce partagé par d'autres utilisateurs ? 

[ https://github.com/emmanuelmrv | [@emmanuelmrv](https://github.com/emmanuelmrv) ] un avis ?

**Comment by ElodieTessier** [comment]
Bonjour,

Cette question avait été évoquée dans l'issue #16 Respecter la casse de l'objet des actes
Nous avions répondu que chaque collectivité allait avoir son propre avis et que dans un soucis d'homogénéisation de la marque blanche, on restait sur la même police pour tous avec la première lettre de l'objet de la délibération en majuscule et en gras.

**Comment by spelhate** [comment]
> * Les lettre P et G par exemple qui sont tronquées dans leur hauteur : @yguenneugues : est-ce faisable facilement ?
Les lettres sont tronquées car une hauteur est spécifiée dans le style css : https://github.com/megalis-bretagne/opendata-marqueblanche/blob/fed36331d02cddea49134a507de94512a6a07caf/resources/css/style.css#L132
En supprimant cette ligne, les lettres ne sont plus tronquées.

**Comment by yguenneugues** [comment]
@spelhate Merci pour l'analyse, je supprime la hauteur dans le css

**Comment by lvinsonneau** [comment]
OK, merci à tous de votre réactivité, en conclusion sur les 2 demandes : 

- Les lettres P et G par exemple qui sont tronquées dans leur hauteur :  **OK**, cela va être pris en compte dans une prochaine version

- La suppression de la majuscule en gras dans le titre du document : **NOK**, difficile de répondre un jour dans un sens à une collectivité et un autre jour dans l'autre sens à une autre... sauf si un jour nous avons un nombre significatif de demandes d'évolution dans le même sens.

**Comment by fmartin44** [comment]
Merci à tous

**Comment by lvinsonneau** [comment]
ça m'a l'air tout bon en pre-prod :
![image](https://user-images.githubusercontent.com/2498403/191755871-478c7175-359b-46a7-86c2-517aaf3b5283.png)

**Comment by fmartin44** [comment]
Oui, parfait.

Merci beaucoup



***@***.***<http://redon-agglomeration.bzh/>
[Facebook Redon Agglomération]<https://www.facebook.com/RedonAgglo/>
Frédéric MARTIN
Chargé des services web et data
02 99 70 34 78

[Twitter Redon Agglomération]<https://twitter.com/redonagglo>
Direction des Systèmes d’Information
3 Rue Charles Sillard, 35600 Redon
02 99 70 34 34




De : lvinsonneau ***@***.***>
Envoyé : jeudi 22 septembre 2022 15:11
À : megalis-bretagne/opendata-marqueblanche ***@***.***>
Cc : Frédéric MARTIN ***@***.***>; Comment ***@***.***>
Objet : Re: [megalis-bretagne/opendata-marqueblanche] Demande pour modifier l'aspect de la iframe Marque Blanche (Issue #23)


ça m'a l'air tout bon en pre-prod :
[image]<https://mibc-fr-01.mailinblack.com/securelink/?url=https://user-images.githubusercontent.com&key=eyJsYW5nIjoiRlIiLCJ1cmwiOiJodHRwczovL3VzZXItaW1hZ2VzLmdpdGh1YnVzZXJjb250ZW50LmNvbS8yNDk4NDAzLzE5MTc1NTg3MS00NzhjNzE3NS0zNTliLTQ2YTctODZjMi01MTdhYWYzYjUyODMucG5nIiwidG9rZW4iOiJnQUFBQUFCakxIRjFGd0V4a202bU9xUnBITnYwOFAwTmJ4Vk9MREhSWWR5OV9LbDhqQnJFUXJlajcwZzZmQ2xPRHV3SGRodUFFMGNERFF6SlhhVk1rZ2ZWc3FZdy1MWVlQenVHSUd2aEZodHdEQURLczFBX1VVSU5VT1BQYmQ5aWs3Tm85ci1kUF9xT00tb0plaTAyVldRYkJrOHcxQVFxOVNxRzZ4QlMtMTd0WnJaQmpsel8xY0x6NnRjd1pSZm5xOTVOUUFybjhnQXB2bk50SHdKWTV1ZGtoU0xFUjB1Qm0wWkVwTVJHRUxkcHhvYmZZUWFXSjFkU01CM0dNNVpNd2NIY1ZacTFVUU1yN3BtUUZnaVFjV2JIUXo0TzNMWDFxbHVxU0lWdktnUHpOek1XVjB4MVJVemczV0g4N25CdnRwTU1EZGIxQlAwYiJ9>

**Comment by yguenneugues** [comment]
installé en production aujourd'hui
