### ISSUE TITLE
Echec chargement fichier des délibérations 2022, données incohérentes sur 1 ligne

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-marqueblanche#24]
Bonjour,

seule  1 ligne bloque le chargement du fichier des délibérations 2022, il s'agit de la ligne n° 14707 du fichier joint qui est incorrectement formatée (extrait de https://www.data.gouv.fr/fr/datasets/r/8a564bff-a7cb-4a8b-8361-b8de8a467e54)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CHRYST~1.RID/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CHRYST~1.RID/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SYNDICAT   MIXTE POUR LA COLLECTE ET LE TRI DES ORDURES MENAGERES DU SECTEUR SUD-EST   D'ILLE ET VILAINE | 25350095300034 | D149_2022 | 13/04/2022 | 1.1 | Commande Publique/Marches   publics | D Fournitures   gilets d'identification     COMMUNE DE BALAZE" | 2,135E+13 | 2022_04_05_D15 | 05/04/2022 | 7.5 | Finances locales/Subventions | OGEC - Subvention Ã    caractÃ¨re social 2022 |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body>

</html>

[deliberation-2022.zip](https://github.com/megalis-bretagne/opendata-marqueblanche/files/9753815/deliberation-2022.zip)

**Comment by Cridard** [comment]
![image](https://user-images.githubusercontent.com/97181939/195059663-1ce67899-2f9e-4484-bf9e-139d359984bb.png)

**Comment by lvinsonneau** [comment]
pb qui est présent chaque mois lors de l'export pour nos stats internes

**Comment by spelhate** [comment]
Voici la ligne qui pose problème
`"SYNDICAT MIXTE POUR LA COLLECTE ET LE TRI DES ORDURES MENAGERES DU SECTEUR SUD-EST D'ILLE ET VILAINE";"25350095300034";"D149_2022";"2022-04-13";"1.1";"Commande Publique/Marches publics";"D Fournitures gilets d'identification 'Accompagnement des événements"";"";"";"";"";"";"";"";"";"";""`

Je pense que l'erreur vient de la double quote à la fin de cette expression
`"D Fournitures gilets d'identification 'Accompagnement des événements""`
![image](https://user-images.githubusercontent.com/1793792/204514557-c5bebcf4-65d0-4612-a9ac-c06c751164e3.png)

**Comment by spelhate** [comment]
En résumé l'erreur provient d'un double quote présent dans l'objet de la délibération. Or les quotes ne semblent pas "échappés" dans la traitement opendata, si bien que les parseurs csv qui utilisent le double quote comme délimiteur de texte s'emmêlent les pinceaux.

**Comment by yguenneugues** [comment]
@spelhate Merci pour l'analyse.
Pour contourner le problème tu peux modifier l'objet depuis l'iHM data-publication avec le crayon.

**Comment by spelhate** [comment]
C'est fait !

**Comment by spelhate** [comment]
Si l'outil de publication permet bien de corriger l'objet qui pose problème, par contre, quand on récupère les données via API https://data-api.megalis.bretagne.bzh/api/v1/scdl/deliberation/253500953/2022, on n'a pas le lien vers le pdf pour l'acte modifié. C'est normal  @yguenneugues ?

**Comment by yguenneugues** [comment]
non ce n'est pas normal...,
 Est ce que c'est un bug lié à la modification de l'objet.

Si tu republies l'acte est ce que l'url vers le doc est présent ?

**Comment by spelhate** [comment]
Oui ça fonctionne en republiant.
Il y a donc un bug dans l'outil de publication. cf https://github.com/megalis-bretagne/opendata-extraction/issues/28
