### ISSUE TITLE
Actes non soumis au TDT : ajouter les arrétés permanents ?

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-marqueblanche#26]
Bonjour,

Deux communes souhaitent récupérer les arrêtés permanents dans la marque blanche de publication des actes.
Est-il possible d'ajouter cette nouvelle catégorie au même titre que les PV de séances, arrêtés temporaires et liste des délib ?
_Je m'interroge aussi sur le côté "permanent" donc sans limite de fin. Est ce gérable dans l'outil de publication ?_

**Arrêté permanent :**

Ces arrêtés sont liés à la circulation. En principe, les arrêtés de police doivent être limités dans le temps et dans l’espace pour pouvoir répondre à l’exigence de l’absence d’interdiction générale et absolue. Cependant, afin de faire face à des travaux urgents ou récurrents, il est possible de prendre un arrêté permanent réglementant la circulation et le stationnement aux abords des travaux et ce à certaines conditions.

**Comment by lvinsonneau** [comment]
C'est peut-être des choses que @spelhate avait abordé avec le dgs de Surzur ?
Je me demande si cela n'avait pas été discuté et finalement tranché au fait que, pour une raison qui m'échappe là maintenant, ce n'était pas la peine de prévoir la rubrique.
Je me demande aussi si @Cridard ne l'a pas évoqué récemment. Elle a peut-être un avis sur la question ?

**Comment by ClaudineHannier** [comment]
Bonjour,
Cette catégorie manquante génère pour nous un gros risque d'oubli de publication. Tous les actes peuvent être enregistrés sur Mégalis (et donc être automatiquement publiés, grâce à la marque blanche) sauf ces arrêtés permanents. Je crains que des arrêtés passent ainsi à la trappe pour la publication.

**Comment by lvinsonneau** [comment]
Merci @ClaudineHannier .
Vous nous confirmez que ce sont des arrêtés qui ne passent pas au contrôle de légalité, c'est bien ça ?
Si oui, je me demandais s'il y avait un intérêt à distinguer les arrêtés temporaires et permanents, ou si un libellé unique "Arrêtés" pouvait suffire ?

**Comment by lvinsonneau** [comment]
Je viens de discuter avec une DGS de collectivité qui me dit qu'elle range les arrêtés permanents dans les actes réglementaires. Donc y'a débat.... Je ne sais pas quelle est la bonne solution. Est-ce possible @ElodieTessier de contacter un service de préfecture ou la DGCL ou le CDG29 sur ce sujet pour éclaircir le point ?

**Comment by ElodieTessier** [comment]
Effectivement @lvinsonneau, il me semble que les deux existent. est ce que vous confirmez @ClaudineHannier ?
Je vais tenter d'éclaircir ce point.

**Comment by spelhate** [comment]
> C'est peut-être des choses que @spelhate avait abordé avec le dgs de Surzur ?

Dans le cadre la publication des arrêtés ne passant pas par le tdt, nous avions identifié 3 types de documents (Liste des délibérations, arrêté temporaire et procès verbal)

**Comment by ClaudineHannier** [comment]
> Merci @ClaudineHannier . Vous nous confirmez que ce sont des arrêtés qui ne passent pas au contrôle de légalité, c'est bien ça ? Si oui, je me demandais s'il y avait un intérêt à distinguer les arrêtés temporaires et permanents, ou si un libellé unique "Arrêtés" pouvait suffire ?

Bonjour, en réalité certains des arrêtés permanents doivent être transmis au  contrôle de la légalité  (ex : arrêtés contre les nuisances sonores).

**Comment by ClaudineHannier** [comment]
> Je viens de discuter avec une DGS de collectivité qui me dit qu'elle range les arrêtés permanents dans les actes réglementaires. Donc y'a débat.... Je ne sais pas quelle est la bonne solution. Est-ce possible @ElodieTessier de contacter un service de préfecture ou la DGCL ou le CDG29 sur ce sujet pour éclaircir le point ?

Nous rangeons également les arrêtés permanents dans les actes réglementaires.

**Comment by lvinsonneau** [comment]
Donc, en guise de synthèse : 

- les arrêtés temporaires : passe par le flux "Actes non soumis au contrôle de légalité" dans la catégorie "Arrêté temporaire"
- les arrêtés permanents : passe par les flux transmis au contrôle de légalité dans la typologie d'actes "Actes réglementaires"

Et donc le fonctionnement actuel répond bien à la demande, c'est bien ça, @ClaudineHannier ?

**Comment by ClaudineHannier** [comment]
Actuellement :  
les arrêtés temporaires : passe effectivement par le flux "Actes non soumis au contrôle de légalité, dans la catégorie "Arrêtés temporaires"
les arrêtés permanents :
passent par les flux transmis au contrôle de légalité dans la typologie d'actes "Actes réglementaires" uniquement pour ceux qui doivent être transmis au contrôle de légalité (ex : pour les arrêtés de nuisance sonore)
les autres arrêtés permanents (ceux qui ne doivent pas être transmis au contrôle de légalité - ex : arrêtés pour l'installation d'une zone à 30km/h )  ne sont pas enregistrés sur Mégalis. Nous devons néanmoins les scanner pour les publier sur notre site internet. Dans les flux "Actes non soumis au contrôle de légalité", il faudrait donc idéalement une catégorie "Arrêtés permanents" pour ce type d'arrêtés permanents.

**Comment by lvinsonneau** [comment]
Merci de ce retour @ClaudineHannier 
Encore une question : avez-vous une source juridique qui explicite les arrêtés permanents soumis au contrôle de légalité et ceux qui ne le sont pas ?

**Comment by ClaudineHannier** [comment]
Bonjour, l'article L2131-2 du CGCT précise que les arrêtés pris par le Maire dans l'exercice de son pouvoir de police doivent être transmis en préfecture (ex: arrêtés lutte contre les bruits de voisinage) mais qu'en sont exclus notamment les arrêtés relatifs à la circulation et au stationnement (ex : instauration permanente d'une zone à 30km/h).

**Comment by lvinsonneau** [comment]
Merci @ClaudineHannier

**Comment by lvinsonneau** [comment]
![image](https://user-images.githubusercontent.com/2498403/228206555-5ef400a9-1baf-43b4-819f-cacc400512d4.png)

Je me pose la question du filtre si nous ajoutons un item "arrêté permanent" dans les actes non soumis au contrôle de légalité, cela engendrera un biais dans les filtres possibles (cf. copie d'écran), car en filtrant selon un nouvel item "arrêté permanent", le citoyen penserait avoir tous les arrêtés permanents (ceux envoyés au contrôle de légalité et ceux non transmis), or, il n'aurait en réalité que les arrêtés permanent non soumis au contrôle de légalité...
En effet, nous ne pouvons les identifier dans la partie actes transmis au contrôle de légalité.

Voilà, est-ce un souci ?

**Comment by ElodieTessier** [comment]
Décision de créer un nouvel item 74 **"arrêtés permanents"** 

A faire en conséquence :
- Flux studio à modifier
- Nouvelle valeur dans le code
- Faire des modifs dans le front et le back

**Comment by PotatoesMaster** [comment]
Bonjour,

Je propose d'ajouter la valeur "AP" (pour arrêtés permanents) à la liste de celles utilisable pour `nature_autre_detail` (nature détaillée de l'acte) dans Pastell.

**Comment by lvinsonneau** [comment]
@syji35 et @Cridard  : ça vous va ?

**Comment by PotatoesMaster** [comment]
Est-ce que vous avez une préférence concernant la position de l'entrée dans la liste ?

![image](https://github.com/megalis-bretagne/opendata-marqueblanche/assets/2265811/cdb832c3-5905-4117-ab23-c354ae07ef9d)

Demande subsidiaire : est-ce vous avez une description que je peux ajouter en infobulle ?

**Comment by ElodieTessier** [comment]
Bonjour,
OK pour l'emplacement.
Infobulle proposée : "Acte administratif permanent relevant des pouvoirs propres au maire et non soumis au contrôle de légalité. Exemples : arrêté permanent de voirie, de circulation, de stationnement et/ou de travaux"
Est ce que ça vous convient ? @lvinsonneau  @syji35 @Cridard ?

**Comment by ElodieTessier** [comment]
Recette OK en prod. Merci

**Comment by ElodieTessier** [comment]
Par contre, manque l'occurrence dans Pastell dans la "nature détaillée de l'acte pour que les collectivités puissent l'utiliser.

**Comment by lvinsonneau** [comment]
Quand peut-on programmer la mise à jour de Pastell ?

**Comment by PotatoesMaster** [comment]
Bonjour @ElodieTessier, @lvinsonneau,  
On vient d'ajouter le code en préprod. Est-ce qu'il serait possible de valider le comportement avant de l'ajouter en prod également ?

**Comment by ElodieTessier** [comment]
Test OK en préproduction. Merci
<img width="711" alt="2024-06-24 10_40_52-Modification du dossier « Actes non soumis au contrôle de légalité » ( MEGALIS B" src="https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97222408/03c4c629-94b5-4781-a1e8-bde8ac165da3">

**Comment by PotatoesMaster** [comment]
Les documents sont bien visibles dans l'interface opendata également ?

**Comment by ElodieTessier** [comment]
Bien présent dans https://data-publication-preprod.megalis.bretagne.bzh/
<img width="784" alt="2024-06-24 11_04_34-Publication opendata — Mozilla Firefox" src="https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97222408/adef8686-dafc-422d-9a92-7819e54bdeb1">

Et dans la MQ blanche en preprod
<img width="916" alt="2024-06-24 11_06_30-Délibérations et actes administratifs — Mozilla Firefox" src="https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97222408/0c412bf7-e297-42f2-ac95-e8e99bc4b40a">

**Comment by lvinsonneau** [comment]
Et types_actes correctement renseigné, cf. https://data-preprod.megalis.bretagne.bzh/?types_actes=74

**Comment by PotatoesMaster** [comment]
Ok, merci beaucoup.

**Comment by PotatoesMaster** [comment]
Et c'est en prod également. Désolé pour le délai.

**Comment by ElodieTessier** [comment]
Testé en PROD, c'est OK ! Merci

**Comment by ElodieTessier** [comment]
c'est OK ! Merci
