### ISSUE TITLE
Demande évolutions en lien avec ticket megalis PLTF-127645 : modifs iframe marque blanche

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-marqueblanche#28]
Bonjour, 
proposition d'évolutions de la collectivité  PLTF-127645 , dixit :

1) Dans l’iframe, serait-il possible, dans les champs de recherche « Types d’actes » (pv de conseil, listes des délibérations, délibérations etc…) d'ajouter « DECISIONS ». En effet, les « décisions du Maire« se retrouvent noyées dans le champ de recherche « Autres ». Or, les « décisions » sont des actes juridiquement important (leur valeur est juste en dessous des délibérations).
   Et serait-il possible de nommer plus précisément les actes selon leur nature ? En effet, tous les actes, quels qu’ils soient sont appelés « décisions. L’idéal serait de les nommer « Délibération du», « Décisions du», « Arrêté du », « Pv du », « Liste du » etc…
![image](https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97181939/b3d613e8-2b07-4eae-9a33-7ca3cf01c34d)

2) serait-il possible :de "bloquer" le critère de tri de i-frames ? En effet, on peut désormais (merci pour cette évolution) définir, dans le code HTML pour l'i-frame, le type d'actes que l'on veut voir afficher. Afin de personnaliser l'i-frame (par exemple un i-frame contenant les délibérations / un autre i-frame séparé contenant les arrêtés réglementaires etc...). Toutefois, lorsque l'i-frame s'affiche concrètement sur le site Web de la commune, rien n'empêche le citoyen d'enlever le filtre pré-défini et donc de voir l'ensemble des actes (délibs, arrêtés) sur une page web qui se destinait à séparer le type d'actes.

**Comment by lvinsonneau** [comment]
Éléments de réponse suite au point data de ce jour : 
 
- **pour la question de convertir le libellé "Décision" en différentes valeurs correspondant aux types d'actes** : non, ce n'est pas possible car les différentes valeurs souhaitées ne sont pas répertoriées pour un champ unique de la base de données

- **pour la question de "bloquer" le filtre pour empêcher qu'il soit supprimé** : à voir s'il est possible de développer un mode "lecture seule" de l'iframe qui serait un nouveau paramètre de l'URL mis à OFF par défaut. Pour avis et discussion @yguenneugues et @syji35

**Comment by lvinsonneau** [comment]
vu en suivi de projet : trop compliqué à développer, donc la demande ne sera pas suivi d'effet
