### ISSUE TITLE
[RECHERCHE] - Saisie directe de date => passer en format français

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-marqueblanche#29]
Bonjour,

Une utilisatrice nous signale une demande d'évolution.
Dans le module de recherche de la marque-blanche "Actes", quand on entre la date via le calendrier : pas de souci, et la date apparaît bien en format "français" (ex. 21/05/2024), mais si on veut entrer une date manuellement et que l'on met "21/05/2024", cela ne marche pas car il attend un format "américain" de type MM/JJ/AAAA

Possible à faire évoluer ?

**Comment by PotatoesMaster** [comment]
Bonjour,

Le comportement est du à une limitation des champs dates de Angular Material lorsqu'on les utilise avec son adaptateur pour les dates natives du navigateur : https://github.com/angular/components/issues/14291.

Il y a d'autres adaptateurs fournis, je vais utiliser celui pour `date-fns` (une bibliothèque pour la manipulation des dates) pour permettre de corriger le problème et d'avoir le même format en affichage et en saisie.

**Comment by ElodieTessier** [comment]
OK, bien fonctionnel et conforme en preprod. Merci !

**Comment by ElodieTessier** [comment]
Recette OK en prod. Merci
