### ISSUE TITLE
maitrise de la publication des annexes

### ISSUE THREAD

**Issue by emmanuelmrv** [megalis-bretagne/opendata-marqueblanche#3]
Bonjour à tous,
Serait-il possible de ne publier que l'acte sans les annexes? Soit tout le temps par défaut, soit de manière optionnelle. C'est bien souvent dans les annexes que se logent des données personnelles.
Cordialement,

**Comment by yguenneugues** [comment]
Bonjour,

Tout est faisable 😜

**Proposition 1 : Simple et rapide à réaliser**
 Ajouter un paramétrage de type oui/non  au niveau de l'organisation (écran paramétrage) pour activer ou non la publication des annexes sur la marque blanche. ( valeur par défaut à définir)

_Faut il prévoir la dépublication de  toutes les annexes déjà publiées lors de la mise en place (si valeur par défaut non)  ? 
En cas de  changement du paramétrage, faut il dépublier toutes les annexes de la collectivité ?_

**Proposition 2 : un peu plus complexe**
Implémenter la solution 1 + permettre depuis le tableau des publications une gestion unitaire des publications des annexes. 
- Deux nouveaux état à gérer  - publié avec annexes /publié sans annexes
- Bouton pour permettre la publication ou dépublication des annexes

**Comment by emmanuelmrv** [comment]
Bonjour,
Je crois que l'option 2 semblerai plus adaptée, car les délibérations sans les annexes peuvent perdre de leur sens.
Mais ceci n'engage que moi.

**Comment by lvinsonneau** [comment]
@clemoigno  : Une question que me pose une collectivité sur cette nouvelle fonctionnalité très attendue : sera-t-il possible de ré-intervenir sur le stock de délibérations et annexes déjà publiées ?

**Comment by clemoigno** [comment]
@lvinsonneau oui, et sauf erreur de ma part, c'est déjà le cas aujourd'hui pour les actes/délibérations. Rien n'empêche de dépublier /republier / redépublier. Cela affecte alors très rapidement les données disponibles sur la marque blanche et impacte la MAJ suivante sur data.gouv (actuellement journalière, opérée la nuit).

Par contre, concernant les annexes liées à l'acte, rien n'est encore fait. Actuellement on ne gère la publication / dépublication qu'au niveau de l'acte, et donc les annexes 'subissent' l'état associé à leur acte. 
Si on descend la possibilité de modifier aussi l'état de publication des annexes (ce qui est l'objet de cette issue), alors on pourra publier/déplublier également chaque annexe individuellement (ce qui n'aura aucune conséquence sur le SCDL qui ne contiennent que le niveau "délibération").

Donc, pour moi oui, ce sera possible.

**Comment by lvinsonneau** [comment]
merci @clemoigno : tu me confirmes que cette possibilité de dissocier la publication des actes et de leurs annexes (objet de cette issue) est bien prévue dans la roadmap de la prochaine version livrée en septembre/octobre prochain ?

**Comment by clemoigno** [comment]
Oui @lvinsonneau .
Question en passant car rien n'est jamais aussi simple qu'il n'y parait : Pour moi, si un acte est dépublié/non publié, automatiquement l'ensemble des annexes sont dépubliées/non publiées de facto sans autre forme de choix de la part de l'utilisateur. Cela n'a aucun sens d'avoir une annexe sans rattachement à un acte ...
La question se pose uniquement pour les actes publiés : l'utilisateur peut alors, éventuellement, dépublier une ou plusieurs annexes liés à l'acte. 
Es-tu en phase avec cela ? @emmanuelmrv un avis ?

**Comment by lvinsonneau** [comment]
Oui @clemoigno, ça parait logique... mais peut-être que @emmanuelmrv aura un autre avis ?

**Comment by emmanuelmrv** [comment]
Bonjour, 
Je suis tout à fait en phase avec ce mode de fonctionnement. 
Bonne journée, 


De: "clemoigno" ***@***.***> 
À: "megalis-bretagne/opendata-marqueblanche" ***@***.***> 
Cc: "Emmanuel MORVAN" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 22 Août 2022 16:34:22 
Objet: Re: [megalis-bretagne/opendata-marqueblanche] maitrise de la publication des annexes (Issue #3) 





Oui [ https://github.com/lvinsonneau | @lvinsonneau ] . 
Question en passant car rien n'est jamais aussi simple qu'il n'y parait : Pour moi, si un acte est dépublié/non publié, automatiquement l'ensemble des annexes sont dépubliées/non publiées de facto sans autre forme de choix de la part de l'utilisateur. Cela n'a aucun sens d'avoir une annexe sans rattachement à un acte ... 
La question se pose uniquement pour les actes publiés : l'utilisateur peut alors, éventuellement, dépublier une ou plusieurs annexes liés à l'acte. 
Es-tu en phase avec cela ? [ https://github.com/emmanuelmrv | @emmanuelmrv ] un avis ?

**Comment by ElodieTessier** [comment]
Bonjour à tous,

Nous venons de clarifier les attendus en interne à partir des éléments de cette issue et des discussions avec d'autres collectivités.

La gestion de la publication des annexes est bien paramétrable depuis l'administration de la Gestion de publication opendata. Les collectivités auront la possibilité de gérer la publication des annexes à deux endroits différents : un premier paramétrage global et un second plus fin pour gérer le statut de publication des annexes à l'acte.

1 - Le principe du tout ou rien :  

Dans le **menu Paramétrage** : ajouter un bouton global pour la publication des annexes "**La publication des annexes des actes est actuellement activé/désactivé**"
![image2023-2-3_14-50-8](https://user-images.githubusercontent.com/97222408/218051144-452946c5-7bae-4ea7-9767-20bf6f122cab.png)
_Dès que cette option est cochée, elle est répercutée sur l'ensemble des annexes des actes quelque soit leur statut de publication. Cette option est répercutée sur tout l'historique de la collectivité._

2 - Choisir le statut de publication des annexes : 
 
Dans **les menus A statuer et Toutes les publications**, pouvoir choisir le statut de publication des annexes des actes publiés sur le même modèle que pour les actes. Voici la proposition que nous faisons, on a bien la création d'un état des annexes avec 2 boutons publier/dé-publier associés.
![image2023-2-3_14-45-29(1)](https://user-images.githubusercontent.com/97222408/218052791-333ca92d-d649-4d80-b59f-bd106eae2ef8.png)
_Les annexes sont liées aux actes, on ne peut pas publier une/des annexes sans son acte. Si un acte est dé-publié alors ses annexes sont automatiquement dé-publiées._ 

Nous ne sommes pas allés plus loin, **pas de changement de statut de publication unitaire des annexes.**

**Comment by emmanuelmrv** [comment]
Bonjour,

Je me pose la question sur ce cas:
1-Un agent active la publication des annexes
2-Ce même agent dé-publie certains jeux d'annexes liés à certains actes.
3-Un second agent se connecte à "la gestion des publications open data" et désactive la publication des annexes, puis se ravise et ré-active cette publication d'annexes.

Question: Est-ce que les paramétrages qui ont été effectués sur l'étape 2 sont conservés?

Merci,

**Comment by ElodieTessier** [comment]
Bonjour à tous,
Merci pour ce retour @emmanuelmrv .
Dans un premier temps, je propose au SIB de répondre sur cet aspect technique : est ce que le statut de publication des annexes est stocké quelque part dans la base SORL ? Si un agent joue sur le paramétrage global, est ce que le statut antérieur est bel et bien conservé ?

**Comment by yguenneugues** [comment]
@emmanuelmrv Le fonctionnement envisagé conservera les dé-publications individuelle.
Nous allons ajouter un nouveau flag pour gérer la désactivation des annexes et ainsi ne pas modifier l'état de toutes les annexes.

**Comment by emmanuelmrv** [comment]
Bonjour,
Oui c'est exactement le comportement attendu.
Merci,

**Comment by gautierrog** [comment]
Si ça vous convient, on pourrait aussi vous proposer une publication / dépublication unitaire des annexes.

Depuis le menu des publications:
- Cela pourrait prendre la forme d'une modale lorsque l'on clique sur un acte. Cette modale listerait les annexes associées avec une option de publication / dépublication *par annexe*.


<strike>Indépendamment de la proposition ci dessus. Il y a une contrainte par rapport à notre modèle que l'on a pas évoqué jusqu'à présent:

- Lorsqu'un agent dépubliera un acte: ses annexes seront bel et bien dépubliées.
<strike>- Si un agent *republie un acte*: toutes ses annexes seront republiées avec (ne garde pas en mémoire la configuration précédente).

Cela ne concerne que la publication/dépublication au niveau de l'acte, pas celui du flag global lié à l'organisation.</strike>

**Comment by gautierrog** [comment]
Disponible en preproduction.

La feature respecte ce qui a été dit ci-dessus. Nous avons cependant été plus loin :

- Au sein du tableau qui gère « Toutes les publications », il est possible de modifier le status de publication des annexes unitairement via un icone supplémentaire dans la rubrique « Actions ».
- Un texte explicatif accompagne le paramétrage global de la publication des annexes.

**Comment by emmanuelmrv** [comment]
Bonjour et merci pour ce retour, 
La republication ne me parait pas être une contrainte. 
Bonne journée, 


Emmanuel MORVAN 
DSI service études et applications - technicien fonctionnel | CCA 
Tél. 02 98 97 35 92 
Parc d’activités de Colguen - 1, rue Victor Schoelcher 
CS 50636 - 29186 CONCARNEAU CEDEX [ http://www.cca.bzh/ ] 




De: "gautierrog" ***@***.***> 
À: "megalis-bretagne/opendata-marqueblanche" ***@***.***> 
Cc: "Emmanuel MORVAN" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Vendredi 14 Avril 2023 10:49:59 
Objet: Re: [megalis-bretagne/opendata-marqueblanche] maitrise de la publication des annexes (Issue #3) 





Si ça vous convient. On pourrait aussi vous proposer une publication / dépublication unitaire des annexes. 

Depuis le menu des publications: 

    * Cela pourrait prendre la forme d'une modale lorsque l'on clique sur un acte. Cette modale listerait les annexes associées avec une option de publication / dépublication par annexe . 


Indépendamment de la proposition ci dessus. Il y a une contrainte par rapport à notre modèle que l'on a pas évoqué jusqu'à présent: 

    * Lorsqu'un agent dépubliera un acte: ses annexes seront bel et bien dépubliées. 
    * Si un agent republie un acte : toutes ses annexes seront republiées avec (ne garde pas en mémoire la configuration précédente). 


Cela ne concerne que la publication/dépublication au niveau de l'acte, pas celui du flag global lié à l'organisation.

**Comment by ElodieTessier** [comment]
Bonjour @gautierrog,
Tout est fonctionnel. J'ai une question :
Est-il possible de fermer directement la fenêtre une fois le choix validé svp ? 
Cela éviterait un clic supplémentaire sur "Fermer" pour fermer la fenêtre.

**Comment by gautierrog** [comment]
@emmanuelmrv 
La contrainte évoquait portait sur la dépublication puis republication d'un acte. 
Cependant, au cours du dev nous avons trouvé une solution et l'outil pourra se souvenir des préférences de dépublication d'annexe dans cette situation aussi.

**Comment by gautierrog** [comment]
> Bonjour @gautierrog, Tout est fonctionnel. J'ai une question : Est-il possible de fermer directement la fenêtre une fois le choix validé svp ? Cela éviterait un clic supplémentaire sur "Fermer" pour fermer la fenêtre.

Oui, j'ai mis à jour en preprod.

**Comment by ElodieTessier** [comment]
> > Bonjour @gautierrog, Tout est fonctionnel. J'ai une question : Est-il possible de fermer directement la fenêtre une fois le choix validé svp ? Cela éviterait un clic supplémentaire sur "Fermer" pour fermer la fenêtre.
> 
> Oui, j'ai mis à jour en preprod.

OK en preprod
