### ISSUE TITLE
[RECHERCHE] Incohérence du nombre de résultats annoncés et comptés

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-marqueblanche#30]
Ci-joint une remarque d'une utilisatrice : 
_"Je m’interroge sur le total indiqué en haut lors de recherche. Par exemple une recherche sur le site de Lamballe-Armor, pour les actes publiés après le 6/7/22 et avant le 7/7/22 indique 25 résultats, alors que la liste n’en compte que 23 et qu’aucun n’a d’annexe"_

Une explication ?

**Comment by yguenneugues** [comment]
https://data.megalis.bretagne.bzh/?siren=200084176&date_debut=2022-07-05T22:00:00.000Z&date_fin=2022-07-06T22:00:00.000Z

**Comment by PotatoesMaster** [comment]
Il y avait un souci dans la gestion des "pages" : l'affichage 10 lignes par 10 perdait une ligne à chaque nouveau chargement au défilement vers le bas (ici sur les documents de 1 à 25, il manquait le 11 et le 22 dans les résultats).

**Comment by ElodieTessier** [comment]
Je viens de vérifier en préprod : https://data-preprod.megalis.bretagne.bzh/?siren=200084176
=> incohérence 24 documents annoncés, 13 présents

**Comment by PotatoesMaster** [comment]
Bonjour @ElodieTessier

Si ce sont toujours les mêmes entrées qui sont affichées, on a 13 actes + 11 annexes = 24 documents.  
Cet affichage est du à une limitation technique : la recherche est faite à la fois sur les actes et les annexes, le nombre de résultats que l'on a comprend les deux.

**Comment by ElodieTessier** [comment]
OK, fonctionnel et répond aux attendus !

**Comment by ElodieTessier** [comment]
Recette OK en prod. Merci
