### ISSUE TITLE
[RECHERCHE] possibilité d'ajouter une recherche par date de décision ?

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-marqueblanche#31]
Y-a-t-il possibilité d'ajouter dans les paramètres de recherche avancée une recherche par date de décision ?

**Comment by ElodieTessier** [comment]
Décision d'ajouter la recherche **"date de décision"** juste au dessus de la recherche par date de publication.
<img width="693" alt="2024-05-21 14_58_46-Suivi projet opendata _ Microsoft Teams" src="https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97222408/a801ead4-798a-47fd-aa31-d96b6fe4f7ed">

**Comment by PotatoesMaster** [comment]
J'ajoute à l'API interne de la marque blanche des critères `date_de_publication_debut` et `date_de_publication_fin` pour filtrer les résultats selon la date de publication. Je réutilise les critères existants `date_debut` et `date_fin` pour filtrer selon la date de décision. De cette manière on garde le nom "date tout court" pour la date de décision à la fois dans l'API et dans le modèle Solr.

**Comment by ElodieTessier** [comment]
OK, bien fonctionnel et conforme en preprod. Merci !

**Comment by ElodieTessier** [comment]
Recette OK en prod. Merci
