### ISSUE TITLE
Gestion de l'accès aux actes individuels dans le cas de collectivités dont plusieurs services utilisent la MQB actes

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-marqueblanche#32]
=> assurer la confidentialité des actes dans les collectivités

Création d'un nouveau rôle :
**utilisateur** (ne peut pas voir les actes individuels) et **utilisateur RH** (par défaut) (peuvent voir les actes individuels)

**Comment by PotatoesMaster** [comment]
Bonjour.

Faut-il permettre aux utilisateurs non-RH de voir les actes individuels déjà publiés ?

Si oui, faut-il permettre aux utilisateurs non-RH de dépublier ces actes individuels ?

**Comment by lvinsonneau** [comment]
Ce n'est que mon avis que je soumets à la communauté pour débat : 
si nous sommes dans la logique de déléguer la gestion de publication des actes RH à un utilisateur dédié, je dirai que l'utilisateur non-RH n'a ni à voir les actes RH ni à modifier leur statut dans le module de gestion de publication. Il pourra consulter les actes RH publié via la marque-blanche comme tout le monde.

Mais preneuse de l'avis de tous : @ElodieTessier @mchabert  @syji35 @Cridard @yguenneugues vos avis ?

**Comment by ElodieTessier** [comment]
Tout à fait d'accord, c'est bien dans cet esprit que nous avions tranché la question.

**Comment by PotatoesMaster** [comment]
Merci beaucoup.

J'ai déployé le filtre en préprod, seuls les utilisateurs RH voit les actes individuels, on pourra bien-sûr compléter par la suite.

**Comment by ElodieTessier** [comment]
OK, bien fonctionnel et conforme en preprod. Merci !
<img width="579" alt="2024-06-06 16_43_04-Publication opendata — Mozilla Firefox" src="https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97222408/ac4b5f2b-2005-4efb-86e9-5d10caf65608">
<img width="584" alt="2024-06-06 16_44_23-Publication opendata — Mozilla Firefox" src="https://github.com/megalis-bretagne/opendata-marqueblanche/assets/97222408/bc25c10a-fac4-4b2f-8925-3e084a0d5529">

**Comment by PotatoesMaster** [comment]
L'accès avec les comptes SA n'a pas été évoqué.

Avec cette modification ils ne verront plus les actes individuels dans "Toutes les publications".

Est-ce que ce comportement vous va ?

**Comment by syji35** [comment]
Oui c'est le bon comportement @PotatoesMaster. Merci de la précision

**Comment by ElodieTessier** [comment]
Recette OK en prod. Merci
