### ISSUE TITLE
filtre des dossiers par année de transmission de la délibération et non par date de publication

### ISSUE THREAD

**Issue by emmanuelmrv** [megalis-bretagne/opendata-marqueblanche#4]
Serait-il possible de classer les délibérations et les annexes par date de transmission en préfecture ou de validation en préfecture?
Aujourd'hui c'est la date de publication des actes et annexes qui classent les documents dans les dossiers 2021 ou 2022.
Si je dé-publie une délibération 2021 et que je la re-publie, cette délibération se range en 2022.

**Comment by lvinsonneau** [comment]
Je n'avais pas encore détecté ce comportement, bien vu, car c'est effectivement un problème.

**Comment by clemoigno** [comment]
Ok pour utiliser la "date de l'acte " issu de pastell dans le classement

**Comment by yguenneugues** [comment]
Corrigé en préprod, on utilise la date de l'acte pour classer dans le bon dossier sur la marque blanche
