### ISSUE TITLE
Permettre la suppression d'une publication

### ISSUE THREAD

**Issue by chrystele1** [megalis-bretagne/opendata-marqueblanche#6]
Bonjour,
à voir comment il serait possible de dépublier des délibérations publiées à tort.
Par exemple sur ce cas d'une même délib de 2021 récupérés depuis l'api https://data-api.megalis.bretagne.bzh/api/v1/scdl/deliberation/2021 qui donne en résultat 3 lignes.
![image](https://user-images.githubusercontent.com/63013157/157704491-6eeea396-7c79-45b6-b505-f7227ed0cdb5.png)

 Il s'agit d'une même délibération ayant fait l'objet de 3 enregistrements dont 2 sont à ignorer : l'une n'est jamais passée par le statut de publication sur PAstell(?), l'autre a été publiée, mais a été annulée sur PASTELL malgré que le flux était en fin de traitement. Pour ce dernier cas, il semble compliquer d'automatiser une dépublication quand une transaction est annulée sur PASTELL mais à voir il serait possible d'agir en aval de pastell, sur l'outil de publication...?
![image](https://user-images.githubusercontent.com/63013157/157700141-6dfd0ce0-f7c6-4adb-9d42-2b633def67b9.png)
Rendu sur l'outil des délibs 👍 
![image](https://user-images.githubusercontent.com/63013157/157704027-76681701-c9d8-47f0-84f5-143372ac5416.png)

lien sur la recherche de l'acte en question : https://pastell.megalis.bretagne.bzh/Document/search?go=go&date_in_fr=true&type=deliberations-studio&id_e=625&lastetat=&last_state_begin=&last_state_end=&etatTransit=&state_begin=&state_end=&search=Election

**Comment by lvinsonneau** [comment]
J'ajoute à la remontée de bug de Chrystèle que nous avons constaté aujourd'hui avec la Mairie de Parigné que non, seulement les délibérations restent dans le service de Publication opendata, mais même si l'utilisateur fait "dépublier", la délibération reste publiée sur le site de la marque blanche

**Comment by clemoigno** [comment]
@chrystele1 @lvinsonneau 
Deux choses ici donc :

1 - Nouvelle fonctionnalités à ajouter côté outil de publication pour pouvoir supprimer littéralement une publication

2 - En effet il semblerait qu'il y ait un souci entre l'état en base et ce que l'on trouve dans la marque blanche pour Parigné. Nous allons instruire cela mais dans un premier temps, peux-tu voir avec Parigné pour refaire une 'dépublication' dans l'outil (on peut le faire, même pour une publication déjà dépublier). Logiquement, cela va fonctionner (on vient de tester). 

Il vaudrait mieux faire une autre issue @lvinsonneau car plusieurs probleme/evo ou question dans le même ticket c'est moins simple à suivre.

**Comment by yguenneugues** [comment]
Livré en preprod
![image](https://user-images.githubusercontent.com/10934427/165740154-f896c9b7-d92d-4caf-afec-fa2e4d6fe87c.png)

**Comment by ElodieTessier** [comment]
Whaouh ! Super, merci Yann !

**Comment by yguenneugues** [comment]
ok je fais ça !
Tu parles bien de ces boutons:
![image](https://user-images.githubusercontent.com/10934427/165748634-c8f34a38-9be8-48a7-8dbe-5475a02e44f6.png)

Je mets valider et annuler ?

**Comment by yguenneugues** [comment]
@ElodieTessier fait et installé en preprod

**Comment by ElodieTessier** [comment]
@yguenneugues Top ! Merci
