### ISSUE TITLE
MARQUE BLANCHE - Masquer les fichiers xml des budgets

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-marqueblanche#7]
Les fichiers xml (budgets) ne sont pas grand public.
Dans le cadre de la réutilisation de la marque blanche dans le site internet d'une commune par exemple, à destination des habitants du territoire,  la publication des fichiers xml ne semble pas opportune.
Est-il possible de récupérer uniquement les délibérations dans l'onglet Budget ?

**Comment by spelhate** [comment]
Si je comprends bien @ElodieTessier , il s'agirait de créer un nouveau paramètre (**type ?**) au niveau de l'API de façon à restreindre ce qui est affiché dans la marque blanche.
Par défaut on récupère tout, mais on aurait la possibilité de filtrer le contenu en précisant le paramètre :

- `type=deliberations` pour afficher les délibérations
- `type=budgets ` pour afficher les budgets

**Comment by ElodieTessier** [comment]
@spelhate 
oui, tu as bien compris
J'imagine un dernier type ou type=NULL qui affiche les délibérations + les budgets pour celles qui le souhaitent.

**Comment by clemoigno** [comment]
Attention cela ne marche pas tout à fait comme vous le dites @ElodieTessier @spelhate .
En fait, l'acte est un budget en lui-même qui est le fichier XML. Seul ce fichier XML est obligatoire dans la transmission du budget.
Ensuite, ce que vous appelez 'délibération', c'est juste la ou les pièces jointes envoyée(s) en annexe avec le fichier budget. Mais ce dernier n'est pas obligatoire. Et surtout, on a aucun moyen de savoir que c'est vraiment une "délibération". C'est juste une annexe.

Ce que l'on peut envisager éventuellement, c'est de ne pas afficher les fichiers de type XML. Mais pour faire cela, il faut revoir le fonctionnement de la marque blanche, qui aujourd'hui affiche 'bêtement' le contenu d'un répertoire.

**Comment by spelhate** [comment]
> Et surtout, on a aucun moyen de savoir que c'est vraiment une "délibération"

Effectivement dans ces conditions, il est plus difficile de filtrer.
Du coup, je ne comprends pas bien comment s'effectue la ventilation délibérations / budgets  dans les deux groupes illustrés ci dessous si on ne sait pas si les documents sont des délibérations ou des budgets ?
![image](https://user-images.githubusercontent.com/1793792/160376954-28dd7610-bfeb-41e9-8dd0-31c8eb1bbb65.png)

**Comment by clemoigno** [comment]
@spelhate 
je crois que c'est un problème de compréhension métier. En fait, dans les flux budget, on trouve le fichier XML qui contient réellement le budget avec sa description, et en plus en PJ on peut avoir divers types de documents, dont la délibération ayant validé le budget. Mais cette délibération ne passe du coup pas par le 'canal' des délibérations standard, et ainsi pas évident de la retrouver.
Voilà pour notre compréhension des choses, mais c'est peut-être à affiner avec des connaisseurs métiers plus pointus.

Comment fait-on la distinction de notre côté : c'est simple, ça dépend uniquement du flux utilisé dans Pastell (à confirmer par @yguenneugues ).

**Comment by yguenneugues** [comment]
La distinction budget/délibération est réalisée avec la méta donnée reçu de pastell **acte_nature** qui correspond  au choix suivant pour un acte générique:

![image](https://user-images.githubusercontent.com/10934427/160386781-a514a7d1-6182-435b-836e-8f0db0637e05.png)

Dans le cas d'un flux studio délibération, il est uniquement possible de sélectionne acte_nature=déliberation:

![image](https://user-images.githubusercontent.com/10934427/160387674-9eb2ef10-10f5-4e58-921f-4b736de76dad.png)

**Comment by lvinsonneau** [comment]
> > Est-il possible de récupérer uniquement les délibérations dans l'onglet Budget ?
> 
> En fait, je crois que je n'avais pas bien compris la demande initiale de @ElodieTessier : filtrer à l'intérieur de budgets et non pas à la racine de la marque blanche.

oui, moi pareil ! car certaines collectivités ont demandé à pouvoir paramétrer l'affichage (oui/non) de ce répertoire budget au sein de la marque-blanche. C'est donc sas doute une autre issue à créer. Ou alors, on peut la traiter dans l'issue https://github.com/megalis-bretagne/opendata-marqueblanche/issues/10 ?

**Comment by ElodieTessier** [comment]
J'aurais du mettre un exemple :
<img width="505" alt="2022-03-28 " src="https://user-images.githubusercontent.com/97222408/160393629-0df86b93-d4a2-404b-8c20-48add0058aaa.png">

**Comment by ElodieTessier** [comment]
Les croix rouges sont les fichiers que les collectivités souhaitent ne pas afficher sur leur site internet.

**Comment by lvinsonneau** [comment]
lié à la nouvelle marque-blanche (automne 2022)
